cordova plugin add call-number
npm install --save @ionic-native/call-number
cordova plugin add cordova-plugin-app-version
npm install --save @ionic-native/app-version
cordova plugin add cordova-plugin-camera
npm install --save @ionic-native/camera
cordova plugin add cordova-plugin-device
npm install --save @ionic-native/device
cordova plugin add cordova-plugin-telerik-imagepicker --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="zkteco.com"
npm install --save @ionic-native/image-picker
cordova plugin add phonegap-plugin-barcodescanner
npm install --save @ionic-native/barcode-scanner
cordova plugin add ionic-plugin-keyboard
npm install --save @ionic-native/keyboard
cordova plugin add cordova-plugin-screen-orientation
npm install --save @ionic-native/screen-orientation
cordova plugin add cordova-sms-plugin
npm install --save @ionic-native/sms
cordova plugin add cordova-plugin-splashscreen
npm install --save @ionic-native/splash-screen
cordova plugin add cordova-plugin-statusbar
npm install --save @ionic-native/status-bar